// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ymNu2hhZMcrWPmwlL7AnAY8CzkWYQMk',
    appId: '1:966190989162:web:e818890c97d348df8eef13',
    messagingSenderId: '966190989162',
    projectId: 'blynd---social-app',
    authDomain: 'blynd---social-app.firebaseapp.com',
    storageBucket: 'blynd---social-app.firebasestorage.app',
    measurementId: 'G-J0ZE1JMG9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeCxn3HPFSRLpeC2Jr20_QT5LbfJTs6Ig',
    appId: '1:966190989162:android:c226f6b180d1d7368eef13',
    messagingSenderId: '966190989162',
    projectId: 'blynd---social-app',
    storageBucket: 'blynd---social-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFpPjns1cilCSF50hW9GfOhtpiMm1HB8I',
    appId: '1:966190989162:ios:9fce1ed3f5e28f6b8eef13',
    messagingSenderId: '966190989162',
    projectId: 'blynd---social-app',
    storageBucket: 'blynd---social-app.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFpPjns1cilCSF50hW9GfOhtpiMm1HB8I',
    appId: '1:966190989162:ios:9fce1ed3f5e28f6b8eef13',
    messagingSenderId: '966190989162',
    projectId: 'blynd---social-app',
    storageBucket: 'blynd---social-app.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );
}
